### ISSUE TITLE
can it add a new feature of export the daily scrum notes as pdf file?

### ISSUE THREAD

**Issue by fengyedou** [ande3577/redmine_daily_scrum#1]
Hi,

Liki wiki or issues, can it provide such export contents as pdf feature?

By the way, I tested on redmine 2.3.2, it works well.

**Comment by ande3577** [comment]
That would be a nice feature.  I'll try to get to it if I can.  Unfortunately in pdf export functionality in the Redmine core is not terribly reusable.

**Comment by fengyedou** [comment]
I see, indeed if redmine can provide office .doc format for exported contents, that will be better, but maybe pdf will be easier for it supports it.I will follow your update, thanks for your work!!

**Comment by fengyedou** [comment]
We are now doing daily scrum meeting minutes manually, if there is a feature to summarize it and can export, it will be good.

**Comment by ande3577** [comment]
Done. Supports exporting a single day's scrum meetings to pdf.

**Comment by fengyedou** [comment]
Thanks, but I tested with a bug, when clicking to pdf for export, there is internal error.

Processing by DailyScrumsController#index as PDF
  Parameters: {"date"=>"2015-02-02", "project_id"=>"xxx"}
  Current user: xxx(id=1)
Completed 500 Internal Server Error in 78ms

ArgumentError (comparison of String with 0 failed):
  lib/redmine/export/pdf.rb:141:in `RDMwriteHTMLCell'

**Comment by ande3577** [comment]
Redmine version?

**Comment by ande3577** [comment]
Never mind, saw it above.

**Comment by ande3577** [comment]
Apparently they changed the interface to the function to parse textilizable fields.  Try out the latest master branch: 4ad8efc0a75755d4d0bd1dd780127baf3e448faf
